---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudschedulersource-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudschedulersources.sources.aikas.org
spec:
  group: sources.aikas.org
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: CloudSchedulerSource
    plural: cloudschedulersources
    singular: cloudschedulersource
  scope: Namespaced
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cloudschedulersource-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cloudschedulersource-controller
  namespace: cloudschedulersource-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cloudschedulersource-controller
  namespace: cloudschedulersource-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudschedulersource-controller
    spec:
      containers:
      - args:
        - -logtostderr=true
        - -stderrthreshold=INFO
        - -raimage
        - us.gcr.io/probable-summer-223122/receiveadapter-ed34e5d5c6278be2ee9b98fdb9ad4d9d@sha256:5db6ef89e1dc9a37772baf7080b3ac7444391483bf48b09738e4fe207eee7eb2
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        image: us.gcr.io/probable-summer-223122/controller-870d05653c81134f2e0c38c2ba82aabd@sha256:943789c2ffd756d2fa61d04e0ecd0f2efe4c97591d11792e66ce5dd5f60b66e4
        name: cloudschedulersource-controller
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      serviceAccountName: cloudschedulersource-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - name: google-cloud-key
        secret:
          secretName: cloudschedulersource-key
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudschedulersource-controller
  namespace: cloudschedulersource-system
