apiVersion: v1
kind: Namespace
metadata:
  name: cloudschedulersource-system

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cloudschedulersources.sources.aikas.org
spec:
  group: sources.aikas.org
  version: v1alpha1
  scope: Namespaced
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    plural: cloudschedulersources
    singular: cloudschedulersource
    kind: CloudSchedulerSource

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cloudschedulersource-controller-admin
subjects:
  - kind: ServiceAccount
    name: cloudschedulersource-controller
    namespace: cloudschedulersource-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cloudschedulersource-controller
  namespace: cloudschedulersource-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudschedulersource-controller
    spec:
      serviceAccountName: cloudschedulersource-controller
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        name: cloudschedulersource-controller
        image: us.gcr.io/probable-summer-223122/controller
        args:
        - "-logtostderr=true"
        - "-stderrthreshold=INFO"
        - "-raimage"
        - "us.gcr.io/probable-summer-223122/receiveadapter"
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      terminationGracePeriodSeconds: 10
      volumes:
      - name: google-cloud-key
        secret:
          secretName: cloudschedulersource-key

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudschedulersource-controller
  namespace: cloudschedulersource-system
