---
apiVersion: v1
kind: Namespace
metadata:
  name: gcssource-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gcssource-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: gcssource-controller
  namespace: gcssource-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcssource-controller
  namespace: gcssource-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcssource-controller
    spec:
      containers:
      - args:
        - -logtostderr=true
        - -stderrthreshold=INFO
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        image: us.gcr.io/probable-summer-223122/controller-8052802edb86bc81e26b390db3d93fe2@sha256:da7ecf1d4eaf0b11951fe84baab3d5b5b01a0ab14dadb67dfe02e112200fc1c0
        name: gcssource-controller
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      serviceAccountName: gcssource-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcssource-key
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
  name: gcssources.sources.aikas.org
spec:
  group: sources.aikas.org
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: GCSSource
    plural: gcssources
    shortNames:
    - gcs
    singular: gcssource
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            bucket:
              description: GCS bucket to subscribe to. For example my-test-bucket
              type: string
            gcpCredsSecret:
              description: Optional credential to use for subscribing to the GCP PubSub
                topic. If omitted, uses gcsCredsSecret. Must be a service account
                key in JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys).
              type: object
            gcsCredsSecret:
              description: Credential to use for creating a GCP notification. Must
                be a service account key in JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys).
              type: object
            googleCloudProject:
              description: Google Cloud Project ID to create the scheduler job in.
              type: string
            objectNamePrefix:
              description: Optional prefix to only notify when objects match this
                prefix.
              type: string
            payloadFormat:
              description: Optional payload format. Either NONE or JSON_API_V1. If
                omitted, uses JSON_API_V1.
              type: string
            serviceAccountName:
              description: Service Account to run Receive Adapter as. If omitted,
                uses 'default'.
              type: string
            sink:
              description: Where to sink the notificaitons to.
              type: object
          required:
          - gcsCredsSecret
          - googleCloudProject
          - bucket
          - sink
  version: v1alpha1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcssource-controller
  namespace: gcssource-system
