apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cloudschedulersource-controller-admin
subjects:
  - kind: ServiceAccount
    name: cloudschedulersource-controller
    namespace: cloudschedulersource-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
