apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gcssource-controller-admin
subjects:
  - kind: ServiceAccount
    name: gcssource-controller
    namespace: gcssource-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
