apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cloudschedulersource-controller
  namespace: cloudschedulersource-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudschedulersource-controller
    spec:
      serviceAccountName: cloudschedulersource-controller
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        name: cloudschedulersource-controller
        image: github.com/vaikas-google/csr/cmd/controller
        args:
        - "-logtostderr=true"
        - "-stderrthreshold=INFO"
        - "-raimage"
        - "github.com/vaikas-google/csr/cmd/receiveadapter"
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      terminationGracePeriodSeconds: 10
      volumes:
      - name: google-cloud-key
        secret:
          secretName: cloudschedulersource-key
