apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcssource-controller
  namespace: gcssource-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcssource-controller
    spec:
      serviceAccountName: gcssource-controller
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        name: gcssource-controller
        image: github.com/vaikas-google/gcs/cmd/controller
        args:
        - "-logtostderr=true"
        - "-stderrthreshold=INFO"
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      terminationGracePeriodSeconds: 10
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcs-source-key
